### ISSUE TITLE
幽灵空白节点，li与li之间的空白

### ISSUE THREAD

**Issue by 1793523411** [1793523411/my-mian-note#6]
问题：两个 display：inline-block 元素放到一起会产生一段空白

**产生空白的原因**

元素被当成行内元素排版的时候，元素之间的空白符（空格、回车换行等）都会被浏览器处理，根据 CSS 中 white-space 属性的处理方式（默认是 normal，合并多余空白），原来 HTML 代码中的回车换行被转成一个空白符，在字体不为 0 的情况下，空白符占据一定宽度，所以 inline-block 的元素之间就出现了空隙

**解决办法**

方法一：

将子元素标签的结束符和下一个标签的开始符写在同一行或把所有子标签写在同一行

方法二：

父元素中设置 font-size: 0，在子元素上重置正确的 font-size

方法三：

为子元素设置 float:left

方法四：

关于方法二，将 li 父级标签字符设置为 0 在 Safari 浏览器依然出现间隔空白，既然设置字符大小为 0 不行，那就将间隔消除了，将下面代码替换方法二的代码，目前测试完美解决。同样随来而来的问题是 li 内的字符间隔也被设置了，我们需要将 li 内的字符间隔设为默认。

```css
.wrap ul {
  letter-spacing: -5px;
}
.wrap ul li {
  letter-spacing: normal;
}
```
